---
language: python
sudo: false
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install pytest

script:
  - pytest -v

notifications:
  email: false
